# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

env:
  global:
  - REPO=$DOCKER_USER/reproducibility_in_plant_pathology
cache: packages

sudo: required

warnings_are_errors: false

language: generic

services:
  - docker

before_install:
  - docker build -t $REPO .

# push our custom docker container to docker hub, env vars stored on travis-ci.org
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/Reproducibility_in_Plant_Pathology
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
